apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: prefix-gitlab-sql # {"$kpt-set":"sql-compute-address-name"}
  namespace: gitlab # {"$kpt-set":"namespace"}
spec:
  address: 10.1.0.0
  addressType: INTERNAL
  location: global
  networkRef:
    name: prefix-gitlab # {"$kpt-set":"network-name"}
  prefixLength: 16
  purpose: VPC_PEERING
---
apiVersion: servicenetworking.cnrm.cloud.google.com/v1beta1
kind: ServiceNetworkingConnection
metadata:
  name: prefix-private-vpc-connection # {"$kpt-set":"private-vpc-connection-name"}
  namespace: gitlab # {"$kpt-set":"namespace"}
spec:
  service: servicenetworking.googleapis.com
  networkRef:
    name: prefix-gitlab # {"$kpt-set":"network-name"}
  reservedPeeringRanges:
  - name: prefix-gitlab-sql # {"$kpt-set":"sql-compute-address-name"}
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: prefix-gitlab-db # {"$kpt-set":"sql-instance-name"}
  namespace: gitlab # {"$kpt-set":"namespace"}
spec:
  databaseVersion: POSTGRES_9_6
  region: us-central1
  settings:
    activationPolicy: ALWAYS
    backupConfiguration:
      startTime: "14:00"
    diskAutoresize: true
    diskSize: 10
    diskType: PD_SSD
    ipConfiguration:
      privateNetworkRef:
        external: projects/a-project-id/global/networks/prefix-gitlab # {"$kpt-set":"network-external"}
    locationPreference:
      zone: us-central1-a
    pricingPlan: PER_USE
    replicationType: SYNCHRONOUS
    tier: db-custom-4-15360
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: prefix-gitlabhq-production # {"$kpt-set":"sql-database-name"}
  namespace: gitlab # {"$kpt-set":"namespace"}
spec:
  instanceRef:
    name: prefix-gitlab-db # {"$kpt-set":"sql-instance-name"}
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: prefix-gitlab # {"$kpt-set":"sql-user-name"}
  namespace: gitlab # {"$kpt-set":"namespace"}
spec:
  instanceRef:
    name: prefix-gitlab-db # {"$kpt-set":"sql-instance-name"}
  password:
    valueFrom:
      secretKeyRef:
        name: prefix-gitlab-db-password
        key: password
---
apiVersion: redis.cnrm.cloud.google.com/v1beta1
kind: RedisInstance
metadata:
  name: prefix-gitlab # {"$kpt-set":"redis-name"}
  namespace: gitlab # {"$kpt-set":"namespace"}
spec:
  authorizedNetworkRef:
    name: prefix-gitlab # {"$kpt-set":"network-name"}
  displayName: Gitlab Redis
  memorySizeGb: 5
  region: us-central1
  tier: STANDARD_HA
