apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: prefix-gitlab # {"$kpt-set":"network-name"}
  namespace: gitlab # {"$kpt-set":"namespace"}
spec:
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: prefix-gitlab # {"$kpt-set":"subnetwork-name"}
  namespace: gitlab # {"$kpt-set":"namespace"}
spec:
  ipCidrRange: 10.0.0.0/16
  networkRef:
    name: prefix-gitlab # {"$kpt-set":"network-name"}
  region: us-central1
  secondaryIpRange:
  - ipCidrRange: 10.3.0.0/16
    rangeName: prefix-gitlab-cluster-pod-cidr # {"$kpt-set":"network-pod-cidr-name"}
  - ipCidrRange: 10.2.0.0/16
    rangeName: prefix-gitlab-cluster-service-cidr # {"$kpt-set":"network-service-cidr-name"}
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: prefix-gitlab # {"$kpt-set":"compute-address-name"}
  namespace: gitlab # {"$kpt-set":"namespace"}
spec:
  addressType: EXTERNAL
  description: Gitlab Ingress IP
  location: us-central1
